### ISSUE TITLE
Calling The OG Delegate In OnAvatarInstantiated Went Brrr

### ISSUE THREAD

**Issue by OFWModz** [charlesdeepk/MultiplayerDynamicBonesMod#10]
Insta Crash PogU

**Comment by PhoxyBoi** [comment]
I'm also experiencing a crash on load of an instance :(

**Comment by OFWModz** [comment]
You can always use VRCAntiCrash in http://discord.me/Poppy ? /shrug

My mod has this for premium users that doesn't break with error avis or
anything, even a better visible check that keeps framerate.

**Comment by charlesdeepk** [comment]
It works now. The mod may (un)expetedbly break in some instances and with some specific avatars due to their unpredictable nature, but otherwise should be good.
