### ISSUE TITLE
VRChat 1031 Update - Button on social quick menu and needs rebuild with new DLLs

### ISSUE THREAD

**Issue by Dervali-git** [charlesdeepk/MultiplayerDynamicBonesMod#13]
With the addition of per user volume control in the base game the per user MDB toggle now overlaps with  the volume control. The button is still usable, just looks bad

![image](https://user-images.githubusercontent.com/68404726/101999401-63b35e00-3ca2-11eb-96cb-dd037d3320fb.png)

Also, at least in my testing MDB needs to be rebuilt with the new DLLs in order to work at all.

**Comment by charlesdeepk** [comment]
Solved in commit #efff838
