### ISSUE TITLE
"Press to enable/disable Dynamic Bones mod" button does not restore original colliders - With suggested fix. 

### ISSUE THREAD

**Issue by Dervali-git** [charlesdeepk/MultiplayerDynamicBonesMod#14]
The button to enable/disable the mod does not restore avatar's original colliders, this is not a new issue, but a long standing one. 

The fix should be simple and I have tested this in my build. The following line should be correct to
https://github.com/charlesdeepk/MultiplayerDynamicBonesMod/blob/50b54e49df37d9a4a634681f25e139680ef4e61e/Main.cs#L1052
`origList.DoIf((x) => ReferenceEquals(x.referenceToOriginal, db), (origData) =>`

**Comment by charlesdeepk** [comment]
Thank you, I have missed that bug for a long time. Fix added in commit 2ccb32.
