### ISSUE TITLE
MelonLoader 0.2.0

### ISSUE THREAD

**Issue by ItsMeZeppelin** [charlesdeepk/MultiplayerDynamicBonesMod#4]
![image](https://user-images.githubusercontent.com/64414315/83347678-1fd9b680-a359-11ea-99e3-a523a59afdd0.png)
Here's the error for the updated ML

[Thank you for taking time in making this, don't overwork yourself, work at your own pace❤]

**Comment by charlesdeepk** [comment]
Added support for MelonLoader support in commit 5ab77214d5a7ecdf1dc4c3fe10ee154c181aa5cd
